name: hotel_booking
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  flutter_localizations:
    sdk: flutter
  hotel_ui_package:
    path: hotel_ui_package  
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  auto_route: ^9.0.3 
  flutter_svg: ^2.0.17
  easy_localization: ^3.0.7+1
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5

dev_dependencies:
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  bloc_test: ^10.0.0
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
