// Mocks generated by Mockito 5.4.4 from annotations
// in hotel_booking/test/features/favorite/view/favorite_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:hotel_booking/core/data/favorite_repository.dart' as _i2;
import 'package:hotel_booking/features/favorite/cubit/favorite_cubit.dart'
    as _i5;
import 'package:hotel_booking/features/favorite/data/hotel_favorite.dart'
    as _i3;
import 'package:hotel_booking/features/hotels/data/models/hotel.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoriteRepository_0 extends _i1.SmartFake
    implements _i2.FavoriteRepository {
  _FakeFavoriteRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHotelRatingInfo_1 extends _i1.SmartFake
    implements _i3.HotelRatingInfo {
  _FakeHotelRatingInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHotelBestOffer_2 extends _i1.SmartFake
    implements _i4.HotelBestOffer {
  _FakeHotelBestOffer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoriteCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteCubit extends _i1.Mock implements _i5.FavoriteCubit {
  @override
  _i2.FavoriteRepository get favoriteRepository => (super.noSuchMethod(
        Invocation.getter(#favoriteRepository),
        returnValue: _FakeFavoriteRepository_0(
          this,
          Invocation.getter(#favoriteRepository),
        ),
        returnValueForMissingStub: _FakeFavoriteRepository_0(
          this,
          Invocation.getter(#favoriteRepository),
        ),
      ) as _i2.FavoriteRepository);

  @override
  List<_i3.HotelFavorite> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: <_i3.HotelFavorite>[],
        returnValueForMissingStub: <_i3.HotelFavorite>[],
      ) as List<_i3.HotelFavorite>);

  @override
  _i6.Stream<List<_i3.HotelFavorite>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<List<_i3.HotelFavorite>>.empty(),
        returnValueForMissingStub: _i6.Stream<List<_i3.HotelFavorite>>.empty(),
      ) as _i6.Stream<List<_i3.HotelFavorite>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void addFavorite(_i4.Hotel? hotel) => super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [hotel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFavorite(String? hotelId) => super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [hotelId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void emit(List<_i3.HotelFavorite>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i7.Change<List<_i3.HotelFavorite>>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRepository extends _i1.Mock
    implements _i2.FavoriteRepository {
  @override
  _i6.Future<void> addFavorite(_i4.Hotel? hotel) => (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [hotel],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFavorite(String? hotelId) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [hotelId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<_i3.HotelFavorite> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: <_i3.HotelFavorite>[],
        returnValueForMissingStub: <_i3.HotelFavorite>[],
      ) as List<_i3.HotelFavorite>);

  @override
  _i6.Stream<List<_i3.HotelFavorite>> watchFavorites() => (super.noSuchMethod(
        Invocation.method(
          #watchFavorites,
          [],
        ),
        returnValue: _i6.Stream<List<_i3.HotelFavorite>>.empty(),
        returnValueForMissingStub: _i6.Stream<List<_i3.HotelFavorite>>.empty(),
      ) as _i6.Stream<List<_i3.HotelFavorite>>);
}

/// A class which mocks [Hotel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotel extends _i1.Mock implements _i4.Hotel {
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get destination => (super.noSuchMethod(
        Invocation.getter(#destination),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#destination),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#destination),
        ),
      ) as String);

  @override
  String get hotelId => (super.noSuchMethod(
        Invocation.getter(#hotelId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#hotelId),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#hotelId),
        ),
      ) as String);

  @override
  _i3.HotelRatingInfo get ratingInfo => (super.noSuchMethod(
        Invocation.getter(#ratingInfo),
        returnValue: _FakeHotelRatingInfo_1(
          this,
          Invocation.getter(#ratingInfo),
        ),
        returnValueForMissingStub: _FakeHotelRatingInfo_1(
          this,
          Invocation.getter(#ratingInfo),
        ),
      ) as _i3.HotelRatingInfo);

  @override
  set ratingInfo(_i3.HotelRatingInfo? _ratingInfo) => super.noSuchMethod(
        Invocation.setter(
          #ratingInfo,
          _ratingInfo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.HotelBestOffer get bestOffer => (super.noSuchMethod(
        Invocation.getter(#bestOffer),
        returnValue: _FakeHotelBestOffer_2(
          this,
          Invocation.getter(#bestOffer),
        ),
        returnValueForMissingStub: _FakeHotelBestOffer_2(
          this,
          Invocation.getter(#bestOffer),
        ),
      ) as _i4.HotelBestOffer);

  @override
  set bestOffer(_i4.HotelBestOffer? _bestOffer) => super.noSuchMethod(
        Invocation.setter(
          #bestOffer,
          _bestOffer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  set images(List<String>? _images) => super.noSuchMethod(
        Invocation.setter(
          #images,
          _images,
        ),
        returnValueForMissingStub: null,
      );
}
