name: hotel_ui_package
description: "A new Flutter package project."
version: 0.0.1
environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4
  test: ^1.25.7
  network_image_mock: ^2.0.1


flutter:
  assets:
    - assets/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/OpenSans-Bold.ttf
          weight: 700